Provide a setting to control how fixed-length field are truncated
MarcosMeli/FileHelpers pull request #363
Opened 2019-10-20 18:28 UTC by Greybird

Hello,

I would like to propose a new setting for fixed-length fields to control how an overflowing value is managed.

Basically, currently, the behavior is to discard characters at the end of the value.
I added a second option, which is to throw an exception when this occurs, as a way to ensure users can be warned if data was lost.
Of course, this could be the foundation to other strategies for handling this case.

Regards,

2019-11-13 16:28 UTC, Greybird commented
Hi @MarcosMeli 

Do you think this PR could be integrated in the next version ?
Do you need further work to be done before it can be considered ? If so, would be happy to fill the gaps!

2019-11-16 01:04 UTC, MarcosMeli commented
HI @Greybird  thanks for your PR !!

I really like idea, lets discuss some things here so we can move forward:

1. I like the idea to default to previous behavior, no breaking changes, I like the idea
2. We need to add a third option that is: KeepToEOL or something like
3. We need to check the attribute is added to the last field of the record
4. We need to add more tests to validate the behavior in record clases with more fields

what do you think ?
Thanks in advance

2019-11-16 13:04 UTC, Greybird commented
Hi,

Thanks for your feedback!

For KeepToEOL, you mean have a behavior that states that the truncation does not occur on the last field of a record ? Wouldn't this be equal to having a field length of int.MaxValue ?
As the overflow occurs on the field level, it is quite strange to me to include a behavior depending on the position.
So I think I might be misinterpreting what you mean, can you please elaborate?

Thanks

2019-12-30 22:59 UTC, Greybird commented
@marcomeli ping?

2020-10-31 11:06 UTC, Greybird commented
Hello!
Any chance to have this PR merged ?
Regards!

2020-10-31 15:44 UTC, mcavigelli commented
Salut Greybird.

I will look into it within the next two weeks.

Bon weekend, Matthias

2020-11-21 18:10 UTC, mcavigelli commented on FileHelpers.Tests/Tests/Common/OverflowModeTests.cs
> +
Could you add another test, that just covers the edge case length=10, text.length = 10 and option Discard?

2020-11-21 18:12 UTC, mcavigelli commented on FileHelpers/Attributes/FieldFixedLengthAttribute.cs
> +        public OverflowMode OverflowMode { get; set; } = OverflowMode.DiscardEnd;
I think here the good documentation should also contain the default behaviour (Discard).

2020-11-21 18:13 UTC, mcavigelli commented on FileHelpers/Fields/FixedLengthField.cs
> +        internal OverflowMode OverflowMode { get; set; }
I think private visibility is sufficient.

2020-11-21 18:16 UTC, mcavigelli commented on FileHelpers/Fields/FixedLengthField.cs
> +            {
The logic for text is split here and in the method GetValueForOverflowingField.
I think it would be better, just to call the method anyway and handle the whole logic there.

2020-11-21 18:20 UTC, mcavigelli requested changes
Hi there

Thank you for your enhancement of the FileHelpers library.
I have added some comments. The changes I suggest are of minor size.

Matthias

2020-11-22 08:00 UTC, Greybird commented on FileHelpers.Tests/Tests/Common/OverflowModeTests.cs
> +
Sure, added some use cases with 9/10/11 too.

2020-11-22 08:07 UTC, Greybird commented
Hi @mcavigelli,

Thanks for your review!
I took your comments into account, and merged master into this branch.
Do not hesitate if you find other enhancements!

Arnaud

2020-11-22 20:31 UTC, mcavigelli commented
Thank you for your quick reply.
I will look into it this week.

Matthias

2020-11-24 21:04 UTC, mcavigelli commented on FileHelpers.Tests/Tests/Common/OverflowModeTests.cs
> +        [TestCase("0123456789ABC", "0123456789")]
Thank you for your extensive tests.

2020-11-24 21:05 UTC, mcavigelli commented on FileHelpers/Attributes/FieldNullValueAttribute.cs
> +        /// Object must be of the correct type
Merci.

2020-11-24 21:06 UTC, mcavigelli approved these changes
Thanks again for your great work.
And thank you for your patience.

Matthias

2020-11-24 21:11 UTC, merged